spbu-coding-2022/trees-6

.github/pull_request_template.md, .gitignore, LICENSE, NOTICE
* Added .gitignore file
* Added Apache License 2.0 
* Added this pull request template :)
Check off the item if the statement is true. Hint: [x] is a marked item.
Please do not delete the list or its items.
=> Added service files .gitignore, license and pull request template

BSTrees/src/main/kotlin/BTree.kt, BSTrees/src/main/kotlin/Node.kt, BSTrees/src/main/kotlin/avlTree/AvlNode.kt, BSTrees/src/main/kotlin/avlTree/AvlTree.kt, BSTrees/src/main/kotlin/balancers/AvlBalancer.kt, BSTrees/src/main/kotlin/balancers/Balancer.kt, BSTrees/src/main/kotlin/balancers/RBBalancer.kt, BSTrees/src/main/kotlin/binarySearchTree/BSNode.kt, BSTrees/src/main/kotlin/binarySearchTree/BSTree.kt, BSTrees/src/main/kotlin/redBlackTree/RBNode.kt, BSTrees/src/main/kotlin/redBlackTree/RBTree.kt
Added tree architecture.
The project will implement: binary search tree, AVL tree and red-black tree
=> Added trees architecture

BSTrees/src/main/kotlin/BTree.kt, BSTrees/src/main/kotlin/Node.kt
* Added implementation of the find function and the updateHeight function
* Fixed codestyle
=> Abstract tree implementation

BSTrees/src/main/kotlin/balancers/Balancer.kt
Added generics to balance due to changes in BTree
=> Fixed Balancer

BSTrees/src/main/kotlin/BTree.kt
Changed NODE_TYPE to nullable type
=> AbstractTree structure changes

BSTrees/build.gradle.kts, BSTrees/src/main/kotlin/avlTree/AvlTree.kt, BSTrees/src/main/kotlin/balancers/AvlBalancer.kt, BSTrees/src/main/kotlin/balancers/BSBalancer.kt, BSTrees/src/main/kotlin/balancers/Balancer.kt, BSTrees/src/main/kotlin/balancers/RBBalancer.kt, BSTrees/src/main/kotlin/redBlackTree/RBTree.kt, BSTrees/src/test/kotlin/balancers/BalancerTest.kt, BSTrees/src/test/kotlin/utils/BSTreeUtil.kt
Fixes:
- Fixed leftRotate() and rightRotate() methods
Features:
- Changed the constructor of the Balancer class for compatibility with the project architecture
- Added automatic tests for Balancer functions
- testLeftRotate()
- testRightRotate()
=> Working version of Balancer

BSTrees/src/main/kotlin/BTree.kt, BSTrees/src/main/kotlin/Node.kt, BSTrees/src/main/kotlin/avlTree/AvlTree.kt, BSTrees/src/main/kotlin/balancers/AvlBalancer.kt, BSTrees/src/main/kotlin/balancers/BSBalancer.kt, BSTrees/src/main/kotlin/balancers/Balancer.kt, BSTrees/src/main/kotlin/balancers/RBBalancer.kt, BSTrees/src/main/kotlin/binarySearchTree/BSTree.kt, BSTrees/src/main/kotlin/redBlackTree/RBNode.kt, BSTrees/src/main/kotlin/redBlackTree/RBTree.kt, BSTrees/src/test/kotlin/balancers/BalancerTest.kt, BSTrees/src/test/kotlin/utils/BSTreeUtil.kt
The architecture of the project has been changed
- The method of storing links between tree vertices has been changed. Now the connections between the vertices are stored in Node.
- Added other new fields in the Node class.
- Rewritten leftRotate and rightRotate methods for the new architecture
- Added BSTree implementation on the new architecture.
BalancerTest class for testing leftRotate and rightRotate methods.
=> Changing the architecture

.github/workflows/CI.yml
Fixed the path to the jar file
=> Small fix in CI file

BSTrees/build.gradle.kts, BSTrees/src/main/kotlin/redBlackTree/RBTree.kt, BSTrees/src/test/kotlin/redBlackTree/RBTreeTest.kt
Added additional tests to check the health of RBTree:
- init null tree
- adding a node
- adding node with equal keys
- big addition test
- deleting a node
- big deletion test
=> Added new tests for RBTree

BSTrees/src/main/kotlin/Node.kt, BSTrees/src/main/kotlin/avlTree/AvlTree.kt, BSTrees/src/main/kotlin/balancers/AvlBalancer.kt, BSTrees/src/main/kotlin/binarySearchTree/BSTree.kt, BSTrees/src/test/kotlin/avlTree/AVLTreeTest.kt, BSTrees/src/test/kotlin/binarySearchTree/BSTreeTest.kt, BSTrees/src/test/kotlin/redBlackTree/RBTreeTest.kt, BSTrees/src/test/kotlin/treeInvariants/TreesInvariants.kt
All AVL and BS trees tests are implemented
Fixed a lot of bugs in BS and AVL trees 
A little bit of refactoring the code
Added comments in assertions
Added automated tests
We provided some automated tests in BSTrees\src\test\kotlin\
There are tests for all the trees and for balancer(rotator)
=> Bs&avl tree tests

BSTrees/src/main/kotlin/BTree.kt, BSTrees/src/main/kotlin/Node.kt, BSTrees/src/main/kotlin/avlTree/AvlNode.kt, BSTrees/src/main/kotlin/balancers/AvlBalancer.kt, BSTrees/src/main/kotlin/balancers/BSBalancer.kt, BSTrees/src/main/kotlin/balancers/Balancer.kt, BSTrees/src/main/kotlin/binarySearchTree/BSNode.kt, BSTrees/src/main/kotlin/binarySearchTree/BSTree.kt, BSTrees/src/main/kotlin/redBlackTree/RBNode.kt, BSTrees/src/main/kotlin/redBlackTree/RBTree.kt
=> Refactoring

BSTrees/src/main/kotlin/avlTree/AvlTree.kt, BSTrees/src/main/kotlin/binarySearchTree/BSTree.kt, BSTrees/src/test/kotlin/avlTree/AVLTreeTest.kt, BSTrees/src/test/kotlin/binarySearchTree/BSTreeTest.kt, BSTrees/src/test/kotlin/redBlackTree/RBTreeTest.kt
=> fix: Fixed a bug with adding equal keys. Fixed the test which checks it

BSTrees/src/test/kotlin/avlTree/AVLTreeTest.kt, BSTrees/src/test/kotlin/binarySearchTree/BSTreeTest.kt, BSTrees/src/test/kotlin/redBlackTree/RBTreeTest.kt
=> added a parameterized test

BSTrees/src/test/kotlin/treeInvariants/TreesInvariants.kt
Fixed a testing bug related to incorrect placement of brackets
=> A small correction of the placement of brackets

.github/workflows/CI.yml, BSTrees/build.gradle.kts, gradle.properties
- Added project build check on 3 types of OS
- Added Jacoco code coverage report
- build.gradle is given a proper look
=> Setting up CI and gradle

BSTrees/src/main/kotlin/serialization/SerializableType.kt, BSTrees/src/main/kotlin/serialization/reps/DBTreeRepo.kt, BSTrees/src/main/kotlin/serialization/reps/JsonTreeRepo.kt, BSTrees/src/main/kotlin/serialization/reps/SQLTables.kt, BSTrees/src/main/kotlin/serialization/reps/SQLTreeRepo.kt
Now trees can be saved in Json
A small manual testing was performed
Tested methods:
- getTree()
- setTree()
- deleteTree()
=> Storing trees in Json

BSTrees/build.gradle.kts, BSTrees/src/main/kotlin/serialization/SerializableType.kt, BSTrees/src/main/kotlin/serialization/reps/DBTreeRepo.kt, BSTrees/src/main/kotlin/serialization/reps/JsonTreeRepo.kt, BSTrees/src/main/kotlin/serialization/reps/Neo4jTreeRepo.kt, BSTrees/src/main/kotlin/serialization/reps/SQLTables.kt, BSTrees/src/main/kotlin/serialization/reps/SQLTreeRepo.kt, gradle.properties
Now trees can be saved in Neo4j
A small manual testing was performed
Tested methods:
getTree()
setTree()
deleteTree()
=> Storing trees in Neo4j

lib/src/main/kotlin/bstrees/dataBases/reps/JsonTreeRepo.kt, lib/src/main/kotlin/bstrees/dataBases/reps/Neo4jTreeRepo.kt, lib/src/main/kotlin/bstrees/dataBases/reps/SQLTreeRepo.kt, lib/src/main/kotlin/bstrees/dataBases/utils/PathsUtil.kt
Added new database class constructor
=> Database class constructor

lib/src/main/kotlin/bstrees/model/dataBases/reps/Neo4jTreeRepo.kt, lib/src/main/kotlin/bstrees/model/dataBases/serialize/strategies/SerializeMethods.kt, lib/src/main/kotlin/bstrees/presenter/TreePresenter.kt, lib/src/main/kotlin/bstrees/presenter/treesPresenters/AvlTreePresenter.kt, lib/src/main/kotlin/bstrees/presenter/treesPresenters/BsTreePresenter.kt, lib/src/main/kotlin/bstrees/presenter/treesPresenters/RbTreePresenter.kt, lib/src/main/kotlin/bstrees/view/assets/TreeView.kt, lib/src/main/kotlin/bstrees/view/screens/TreeScreen.kt
- Added the ability to add and delete a node from SerializableTree (early version)
- Fixed the error of searching and deleting the tree in Neo4j
=> UI Presenter

app/src/main/kotlin/app/presenter/LayoutPresenter.kt, app/src/main/kotlin/app/presenter/utils/TreeHeightPresenter.kt
Added an easy algorithm to determine the location of tree vertices.
=> LayoutPresenter implementation

app/src/main/kotlin/app/presenter/TreePresenter.kt, lib/build.gradle.kts, lib/src/main/kotlin/bstrees/model/dataBases/converters/TreeToDataConverter.kt, lib/src/main/kotlin/bstrees/model/dataBases/converters/treesConverters/AvlToDataConverter.kt, lib/src/main/kotlin/bstrees/model/dataBases/converters/treesConverters/RandomBsToDataConverter.kt, lib/src/main/kotlin/bstrees/model/dataBases/converters/treesConverters/RbToDataConverter.kt, lib/src/main/kotlin/bstrees/model/dataBases/reps/JsonTreeRepo.kt, lib/src/main/kotlin/bstrees/model/trees/BSNode.kt, lib/src/main/kotlin/bstrees/model/trees/BSTree.kt, lib/src/main/kotlin/bstrees/model/trees/Balancer.kt, lib/src/main/kotlin/bstrees/model/trees/avl/AvlNode.kt, lib/src/main/kotlin/bstrees/model/trees/avl/AvlTree.kt, lib/src/main/kotlin/bstrees/model/trees/randomBinarySearch/RandomBSBalancer.kt, lib/src/main/kotlin/bstrees/model/trees/randomBinarySearch/RandomBSNode.kt, lib/src/main/kotlin/bstrees/model/trees/randomBinarySearch/RandomBSTree.kt, lib/src/main/kotlin/bstrees/model/trees/redBlack/RBNode.kt, lib/src/main/kotlin/bstrees/model/trees/redBlack/RBTree.kt, lib/src/test/kotlin/avlTree/AVLTreeInvariants.kt, lib/src/test/kotlin/balancers/BalancerTest.kt, lib/src/test/kotlin/binarySearchTree/BSTreeInvariants.kt, lib/src/test/kotlin/binarySearchTree/RandomBSTreeTest.kt, lib/src/test/kotlin/converters/TreeToDataConverterTest.kt, lib/src/test/kotlin/dataBases/JsonTreeRepoTest.kt, lib/src/test/kotlin/dataBases/SQLTreeRepoTest.kt, lib/src/test/kotlin/redBlackTree/RBTreeInvariants.kt, lib/src/test/kotlin/utils/BSTreeUtil.kt, lib/src/test/kotlin/utils/TreeDataUtil.kt, lib/src/test/kotlin/utils/TreesInvariants.kt
- Added tests for JsonRepo and SQLRepo.
- Neo4jRepo is not tested due to the complex testing of this kind of databases on github.
- Added tests for all types of converters
BSTree -> RandomBSTree
BSNode -> RandomBSNode
BSBalancer -> RandomBSBalancer
BTree -> BSTree
Node -> BSNode
=> Database and converters testing

app/src/main/kotlin/app/view/App.kt, app/src/main/kotlin/app/view/assets/DatabaseConnections.kt, app/src/main/kotlin/app/view/assets/Selector.kt, app/src/main/kotlin/app/view/screens/ChosingTypesScreen.kt, app/src/main/kotlin/app/view/screens/HomeScreen.kt, app/src/main/kotlin/app/view/screens/TreeScreen.kt
Fixed choice menu. Added a lot of visual hints. Fixed spaces beetwen objects
=> Appearance changes
